messages:
  prefix: "&e[LB-LuckyBlock] "
  reload: "&aKonfigurasyon basariyla yenilendi."
  no-permission: "&cBu komutu kullanmak icin yetkiniz yok!"
  given-item: "&a%player% isimli oyuncuya Sans Blogu verildi!"
  block-placed: "&aSans Blogu basariyla yerlestirildi!"
  block-removed: "&cSans Blogu kaldirildi!"
  macro-warning: "&cCok hizli vuruyorsunuz! Lutfen makro kullanmayiniz."
  block-destroyed: "&e%player%, &e&lSANS BLOĞU&e'nu patlatti! Oduller sacildi!"
  block-respawning: "&e&lSANS BLOĞU &ayenileniyor... Lutfen bekleyin."
  block-respawned: "&e&lSANS BLOĞU &ayenilendi! Tekrar vurabilirsiniz."

macro-protection:
  max-cps: 5

lucky-block-item:
  material: "BUBBLE_CORAL"
  name: "&e&lŞANS BLOĞU"
  lore:
    - "&7Bu blogu yere koyarak"
    - "&7Sans Blogu olusturabilirsiniz."

blok-ayarlari:
  display-name: "&e&lŞANS BLOĞU"
  max-hits: 20
  respawn-delay-seconds: 15
  sounds:
    hit: "BLOCK_NOTE_BLOCK_PLING"
    break: "ENTITY_GENERIC_EXPLODE"
